<a href="https://colab.research.google.com/github/salonii1030/GUVI-Machine_Learning-Task_7/blob/main/KNN_Task_7_Assgn_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from scipy.spatial import distance

In [ ]:
train = pd.read_csv("trainKNN.txt", header=None)
train.columns = ['Id', 'RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe', 'Type']
train = train.drop('Id', axis=1)
test = pd.read_csv('testKNN.txt', header=None)
test.columns=['Id', 'RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe', 'Type']
test = test.drop('Id', axis=1)

In [ ]:
def standardize (df):
    for i in df.columns:
        if i != "Type": 
            df[i] = (df[i] - df[i].mean())/df[i].std()
    return df

In [ ]:
train = standardize(train)
test = standardize(test)
train.head()
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# train = scaler.fit_transform(train)
# test = scaler.transform(test)

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
0,0.888537,0.338119,1.242977,-0.720654,-1.120263,-0.682898,-0.113060,-0.33849,-0.581932,1
1,-0.224221,0.657345,0.603903,-0.191863,0.123880,-0.058551,-0.760269,-0.33849,-0.581932,1
2,-0.692234,0.197659,0.568000,0.174223,0.464382,-0.192340,-0.795443,-0.33849,-0.581932,1
3,-0.207857,-0.210950,0.668529,-0.334230,-0.033275,0.075237,-0.485909,-0.33849,-0.581932,1
4,-0.286405,-0.134335,0.618265,-0.435920,0.582248,0.045506,-0.591432,-0.33849,-0.581932,1

In [ ]:
sqeucl_model = KNeighborsClassifier(n_neighbors = 4, metric=distance.sqeuclidean) 
manhattan_model = KNeighborsClassifier(n_neighbors = 4, metric=distance.cityblock) 
x_train = train.drop(["Type"], axis=1)
y_train = train["Type"]
sqeucl_model.fit(x_train,y_train)
manhattan_model.fit(x_train, y_train)
x_test = test.drop("Type", axis=1) 
y_test = test["Type"]

In [ ]:
man_pred = manhattan_model.predict(x_test)

In [ ]:
euc_pred = sqeucl_model.predict(x_test)

In [ ]:
df_pred = pd.DataFrame({"Actual": y_test, "Euclidean": euc_pred,"Manhattan":man_pred})

In [ ]:
df_pred

    Actual  Euclidean  Manhattan
0        1          1          1
1        1          1          1
2        1          1          1
3        2          2          2
4        2          2          2
5        2          1          1
6        3          2          2
7        3          2          2
8        3          1          1
9        5          5          5
10       5          2          2
11       5          5          5
12       6          6          6
13       6          2          6
14       6          7          2
15       7          7          7
16       7          7          7
17       7          7          7

In [ ]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

print("Accuracy for Sq.Euclidean: ",accuracy_score(y_test, euc_pred))
print(classification_report(y_test, euc_pred))
print("\n")
print("Accuracy for Manhattan: ",accuracy_score(y_test,man_pred),"\n")
print(classification_report(y_test, man_pred))

Accuracy for Sq.Euclidean:  0.6111111111111112
              precision    recall  f1-score   support

           1       0.60      1.00      0.75         3
           2       0.33      0.67      0.44         3
           3       0.00      0.00      0.00         3
           5       1.00      0.67      0.80         3
           6       1.00      0.33      0.50         3
           7       0.75      1.00      0.86         3

    accuracy                           0.61        18
   macro avg       0.61      0.61      0.56        18
weighted avg       0.61      0.61      0.56        18



Accuracy for Manhattan:  0.6666666666666666

              precision    recall  f1-score   support

           1       0.60      1.00      0.75         3
           2       0.33      0.67      0.44         3
           3       0.00      0.00      0.00         3
           5       1.00      0.67      0.80         3
           6       1.00      0.67      0.80         3
           7       1.00      1.00      1.00         3

    accuracy                           0.67        18
   macro avg       0.66      0.67      0.63        18
weighted avg       0.66      0.67      0.63        18

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))